py_library(
  name = "openflight_video",
  srcs = glob(["openflight_video/src/**/*.py"]),
  deps = [],
  visibility = ["//visibility:public"],
)

py_library(
  name = "openflight_audio",
  srcs = glob(["openflight_audio/src/**/*.py"]),
  deps = [],
  visibility = ["//visibility:public"],
)