package(default_visibility = ["//visibility:public"])

load("@openflight_components//video:deps.bzl", "video_deps")

py_library(
  name = "openflight",
  srcs = glob(["src/**/*.py"]),
  deps = [
    video_deps,
  ],
)
